[package]
name = "riscan-pro"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
docopt = "*"
las = { git = "https://github.com/gadomski/las-rs.git" }
nalgebra = "*"
pbr = "*"
rustc-serialize = "*"
xmltree = "0.3"
