[package]
name = "riscan-pro"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
description = "Query RiSCAN Pro projects"
repository = "https://github.com/gadomski/riscan-pro"
readme = "README.md"
keywords = ["lidar", "riegl", "riscan"]
license = "MIT"

[dependencies]
alga = "0.5"
nalgebra = "0.13"
sxd-xpath = "0.4"
sxd-document = "0.2"

[dev-dependencies]
approx = "0.1"
