[package]
name = "riscan-pro"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
docopt = "0.6"
las = "0.3"
nalgebra = "0.9"
pbr = "0.3"
rustc-serialize = "0.3"
xmltree = "0.3"

[[bin]]
name = "riscan-pro"
doc = false
